version: '3.8'

services:
  php:
    build: ./php
    container_name: app
    ports:
      - "80:80"
    depends_on:
      - db_vero_digital
    restart: always
    
    

  db_vero_digital:
    image: mcr.microsoft.com/mssql/server:2022-latest
    ports:
      - "1433:1433"
    container_name: mssql-server
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=Un!q@to2023
      # - APACHE_SERVER_NAME=localhost
    volumes:
      - mssql-srv:/var/opt/mssql
# Define the volume
volumes:
  mssql-srv:




