version: '3.8'
services:
  mssql-server:
    build:
      context: .
      dockerfile: mssql.dockerfile
    # ports:
    # - "1433:1433"
    networks:
      - my-network

  web-server:
    build:
      context: .
      dockerfile: webserver.dockerfile
    ports:
      - "8080:80"
    depends_on:
      - mssql-server
    networks:
      - my-network

networks:
  my-network:
